version: '3'
services:
  api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
      - "5566:5566"
    command: ["python", "app.py"]
  pdf:
    image: samuelcolvin/pydf
    ports:
      - "8011:80"
