version: '3'
services:
  api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"  # Main RPC (pub)
      - "5556:5556"  # Main RPC (sub)
      - "5566:5566"  # Image RPC
      - "5577:5577"  # Image RPC
      - "5000:5000"  # Flask
    command: "./run.sh"
  pdf:
    image: samuelcolvin/pydf
    ports:
      - "8011:80"
